### ISSUE TITLE
Article: Profiling Substrate

### ISSUE THREAD

**Issue by gnunicorn** [substrate-developer-hub/knowledgebase#31]
How to profile substrate – setup guide and best practices to profile for CPU/memory/whatever.

**Comment by joepetrowski** [comment]
Fits in nicely with https://github.com/substrate-developer-hub/knowledgebase/issues/1

**Comment by gnunicorn** [comment]
first stab at memory profiling. Feedback (and inline changes) appreciated!

https://hackmd.io/4uuO2o7HQIWZbkEo6NAV9w

Edit: Added some more information regarding log size, and tips for managing it.

**Comment by wheresaddie** [comment]
migrating and adapting/editing .. moving to  knowledgebase/integrate/memory-profiling.md

assigned to PR @gnunicorn @joepetrowski
