### ISSUE TITLE
Update all rustdocs links

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/knowledgebase#41]
Now that our crates are published on crates.io, our docs are also published on docs.rs.

We should replace all `substrate.dev/rustdocs` links with the corresponding docs.rs links. For example https://docs.rs/sc-service/ (which points to latest published version) or https://docs.rs/sc-service/0.8.0-alpha.3/sc_service/ which points to a specific version.

context: https://github.com/paritytech/substrate/issues/5652

**Comment by JoshOrndorff** [comment]
Thinking about it more, I guess the KB is not versioned, so it probably makes sense to point to the latest published docs.

**Comment by danforbes** [comment]
Should we use `crates.parity.io` for this since it is pinned to the latest version and allows searching across multiple crates?

**Comment by JoshOrndorff** [comment]
Update. The devhub team has decided not to rely on docs.rs for linking to our reference docs. The primary reason is that docs.rs does not provide cross-crate search. So if I'm on the docs for `sc-service` and I search for "LongestChain", I won't find anything because that struct does not live in `sc-service`.

We've decided to continue supporting substrate.dev/rustdocs, and move them over to substrate.io whenever we can get the DNS set up properly.
