### ISSUE TITLE
Runtime storage

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/knowledgebase#5]
The last month has seen an overhall of storage keys in Substrate. Add documentation about how storage keys are created (key elements + hasher), how to access storage from within the runtime, and how to query storage values over RPC.

Useful:
- https://github.com/paritytech/substrate/blob/c34e0641abe52249866b62fdb0c2aeed41903be4/frame/support/procedural/src/lib.rs
- https://github.com/paritytech/substrate/pull/5226

**Comment by JoshOrndorff** [comment]
Related: https://substrate.dev/recipes/3-entrees/storage-api/storage-maps.html
