### ISSUE TITLE
List Substrate Client Libraries

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/knowledgebase#50]
We should include a list of client libraries in various languages for interacting with the Substrate RPC server.

**Comment by danforbes** [comment]
This information could potentially go on a new "RPC" page under [the Integrate section](/substrate-developer-hub/knowledgebase/tree/master/current/integrate).

**Comment by joepetrowski** [comment]
Can basically copy: https://wiki.polkadot.network/docs/en/build-tools-index
