### ISSUE TITLE
Document paritydb in advanced/storage

### ISSUE THREAD

**Issue by Swader** [substrate-developer-hub/knowledgebase#55]
It's not even mentioned right now, but it's quite stable and a usable "early adopter" option worth documenting.

**Comment by joepetrowski** [comment]
Closing for https://github.com/substrate-developer-hub/knowledgebase/issues/60. It's a good idea but really has nothing to do with advanced/storage, which is meant for runtime developers. The underlying DB doesn't change runtime development.
