### ISSUE TITLE
Setup translation workflow for substrate.io

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/knowledgebase#69]
Thanks for the reporting from @SotaWatanabe .

As substrate.io will be stable and replace devhub soon, having multi-language support in the new site would be helpful for dev users who are not using English as native.
The existing translations can be migrated through the new workflow, so no more repeated work.

The structure of substrate.io should already be able to support multi-language from @thisisvilla , it's just not clear how to come to a best practice to consolidate the old work, frequently changed docs, and which tool to auto the workflow, etc.

We could potentially use Crowdin, but there could be other tools.

CC @jimmychu0807

**Comment by jimmychu0807** [comment]
Move to: https://github.com/paritytech/substrate.io/issues/80
