### ISSUE TITLE
Document macros used in Substrate

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/knowledgebase#70]
Current knowledge base macro page: 
https://github.com/substrate-developer-hub/knowledgebase/blob/master/current/runtime/macros.md

But it will be great if we can go into detail to describe each frequently used macros

In runtime
- [ ] parameter_types!
- [ ] construct_runtime!

In pallet
- [ ] decl_storage!
- [ ] decl_event!
- [ ] decl_module!
- [ ] decl_error!
- [ ] app_crypto!

In testing
- [ ] impl_outer_origin!
- [ ] impl_outer_event!

**Comment by danforbes** [comment]
Closed by https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/585
