### ISSUE TITLE
Article on the structure of a block

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/knowledgebase#81]
It would summarize the Block and Header traits and their generic implementations.

https://crates.parity.io/sp_runtime/generic/struct.Block.html
https://crates.parity.io/sp_runtime/traits/trait.Block.html
https://crates.parity.io/sp_runtime/generic/struct.Header.html
https://crates.parity.io/sp_runtime/traits/trait.Header.html

**Comment by joepetrowski** [comment]
We have a very high level of this: https://substrate.dev/docs/en/knowledgebase/learn-substrate/extrinsics#block-structure
